name: oh-thanks

services:
  mongo:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - oh-thanks-network
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - oh-thanks-network
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - oh-thanks-network
    command: npm run dev -- --host
    depends_on:
      - api

  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - oh-thanks-network
    depends_on:
      - api
      - frontend

volumes:
  mongo_data:
  caddy_data:
  caddy_config:

networks:
  oh-thanks-network:
    driver: bridge